title: San Joaquin Valley Secion of ACS
# author: GitHub User
email: sjvs.acs.contact@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Local Section of the American Chemical Society

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sjvacs
    github:  sjvacs
    facebook: sjvacs

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
